# Generated by Django 4.2.16 on 2024-12-11 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 11, 3, 35, 59, 67804), verbose_name='Дата комментария'),
        ),
    ]
